# Import Libraries

In [0]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

# Generating Data

In [2]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3500, 3250, 3500, 3750, 4000, 4250])
m= len(X1)

print(f'Years of work: {X1}')
print(f'Salary: {Y}')
print(f'Number of Samples: {m}')

Years of work: [1 2 3 4 5 6]
Salary: [3500 3250 3500 3750 4000 4250]
Number of Samples: 6


# Preprocesing Data

In [3]:
X1 = X1.reshape(m,1)
Y = Y.reshape(-1,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [4]:
bias = np.ones((m,1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [5]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


# Random initialization of prarmeters

In [6]:
eta = 0.01
weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.49671415]
 [-0.1382643 ]]


# Simple gradient method

In [7]:
intercept = []
coef = []

for i in range(3000):
  gradient = (2 / m)* X.T.dot(X.dot(weights) -Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[3083.28362049]
 [ 178.58304047]]


In [8]:
df= pd.DataFrame(data={'intercept':intercept, 'coef':coef})
df.head()

intercept        coef
0   74.663125  269.868906
1  128.445706  452.782252
2  168.348701  576.447103
3  198.797096  659.807073
4  222.801326  715.749797

# Matching Visualization


In [9]:
px.line(df, y ='intercept', width=800,title='Matching: intercept')

In [10]:
px.line(df, y='coef', width=800, title='Matching: coef')