# Loading tensorflow library

In [11]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.2.0'

# Introduction - first model

In [14]:
# create an instance of the class Sequential
from tensorflow.keras.models import Sequential

model= Sequential()
print(model)

In [0]:
from tensorflow.keras.layers import Dense
model.add(Dense(units=4, input_shape=(10, )))

Display and summary model

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Add another layers

In [17]:
model.add(Dense(units=2))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 4)                 44        
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


# Usage of activations

In [18]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data= pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [19]:
px.line(data, x='data', y='linear', width=500,height=500, range_y=[-3,3])

In [22]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [23]:
px.line(data, x='data', y='sigmoid', width=500, height=500, range_y=[-0.5,1.5])

In [25]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [26]:
px.line(data, x='data', y='relu', width=500, height=500, range_y=(-0.5,1.5))

In [27]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data':random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [28]:
px.line(data, x='data', y='tanh', width=500, height=500, range_y=(-2,2))

In [29]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


# Compile Model

In [0]:
# binary classification
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
# multi-class classification
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
# regression
model.compile(optimizer='rmsprop',
              loss='mse')

# Training Model

In [0]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, 
#           validation_data=(x_val, y_val))

# Example binary classification

In [32]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [33]:
data[:3]

array([[ 0.79803687,  0.28760851, -2.01756478, -1.25126197, -1.13991112,
        -2.5403842 ,  0.74288658, -1.13183841, -0.1134749 ,  2.34144354,
        -0.42416148,  0.65797485,  0.75838808,  0.39604294, -0.04061754,
         1.4997749 , -1.15194559, -1.75403253, -0.26498228,  0.74071261,
        -0.37548006,  0.54366715, -0.97396806, -2.1384749 , -0.78700132,
        -0.97959067, -0.35166426,  1.65439815,  0.60154908, -0.34330647,
         1.460543  , -1.25186684, -0.5644469 ,  1.30106366,  0.31569647,
        -0.04834585, -0.81649122,  1.9248879 ,  0.43694087,  1.2240738 ,
        -0.41255134, -1.64432214, -1.44417515,  0.11096844,  0.1449737 ,
         0.22878216, -0.28906505, -0.31150415,  0.52875368,  0.07504563,
         1.74759702,  0.7444349 , -0.68149438,  0.63207736, -1.37758311,
        -0.03990826,  1.412647  , -0.14227356,  0.71200659, -2.1185159 ,
         0.32063269, -0.4143354 ,  1.4161837 ,  1.9781799 ,  0.60941441,
        -1.0929311 ,  0.66352289,  0.04446901, -1.1

In [34]:
labels[:10]

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [36]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.7715 - accuracy: 0.4987
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6964 - accuracy: 0.5444
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6746 - accuracy: 0.5740
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6593 - accuracy: 0.6068
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6448 - accuracy: 0.6276
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6307 - accuracy: 0.6461
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6161 - accuracy: 0.6666
Epoch 8/20
313/313 [==============================] - 0s 2ms/step - loss: 0.6022 - accuracy: 0.6812
Epoch 9/20
313/313 [==============================] - 0s 2ms/step - loss: 0.5891 - accuracy: 0.6982
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5760 - accuracy: 0.7040

In [38]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
334/334 [==============================] - 0s 1ms/step - loss: 0.7548 - accuracy: 0.4967
Epoch 2/20
334/334 [==============================] - 0s 1ms/step - loss: 0.6974 - accuracy: 0.5453
Epoch 3/20
334/334 [==============================] - 0s 1ms/step - loss: 0.6770 - accuracy: 0.5746
Epoch 4/20
334/334 [==============================] - 0s 1ms/step - loss: 0.6611 - accuracy: 0.5991
Epoch 5/20
334/334 [==============================] - 0s 1ms/step - loss: 0.6473 - accuracy: 0.6270
Epoch 6/20
334/334 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6441
Epoch 7/20
334/334 [==============================] - 1s 1ms/step - loss: 0.6184 - accuracy: 0.6631
Epoch 8/20
334/334 [==============================] - 0s 1ms/step - loss: 0.6057 - accuracy: 0.6793
Epoch 9/20
334/334 [==============================] - 0s 1ms/step - loss: 0.5909 - accuracy: 0.6943
Epoch 10/20
334/334 [==============================] - 0s 1ms/step - loss: 0.5777 - accuracy: 0.7069

In [39]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2)

Epoch 1/20
267/267 [==============================] - 1s 3ms/step - loss: 0.7627 - accuracy: 0.5005 - val_loss: 0.7331 - val_accuracy: 0.4990
Epoch 2/20
267/267 [==============================] - 0s 2ms/step - loss: 0.6939 - accuracy: 0.5480 - val_loss: 0.7318 - val_accuracy: 0.4880
Epoch 3/20
267/267 [==============================] - 1s 2ms/step - loss: 0.6716 - accuracy: 0.5813 - val_loss: 0.7290 - val_accuracy: 0.5015
Epoch 4/20
267/267 [==============================] - 0s 2ms/step - loss: 0.6533 - accuracy: 0.6164 - val_loss: 0.7351 - val_accuracy: 0.5040
Epoch 5/20
267/267 [==============================] - 1s 2ms/step - loss: 0.6376 - accuracy: 0.6409 - val_loss: 0.7430 - val_accuracy: 0.5035
Epoch 6/20
267/267 [==============================] - 0s 2ms/step - loss: 0.6221 - accuracy: 0.6649 - val_loss: 0.7414 - val_accuracy: 0.5080
Epoch 7/20
267/267 [==============================] - 0s 2ms/step - loss: 0.6059 - accuracy: 0.6789 - val_loss: 0.7474 - val_accuracy: 0.5215
Epoch 

In [40]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.3, 
          verbose=0)

In [45]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.3, 
          verbose=1)

Epoch 1/20
234/234 [==============================] - 1s 2ms/step - loss: 0.7453 - accuracy: 0.5143 - val_loss: 0.7339 - val_accuracy: 0.4960
Epoch 2/20
234/234 [==============================] - 0s 2ms/step - loss: 0.6909 - accuracy: 0.5523 - val_loss: 0.7271 - val_accuracy: 0.5003
Epoch 3/20
234/234 [==============================] - 0s 2ms/step - loss: 0.6706 - accuracy: 0.5909 - val_loss: 0.7281 - val_accuracy: 0.5093
Epoch 4/20
234/234 [==============================] - 0s 2ms/step - loss: 0.6540 - accuracy: 0.6116 - val_loss: 0.7280 - val_accuracy: 0.5093
Epoch 5/20
234/234 [==============================] - 0s 2ms/step - loss: 0.6390 - accuracy: 0.6410 - val_loss: 0.7350 - val_accuracy: 0.5013
Epoch 6/20
234/234 [==============================] - 0s 2ms/step - loss: 0.6238 - accuracy: 0.6620 - val_loss: 0.7439 - val_accuracy: 0.5000
Epoch 7/20
234/234 [==============================] - 0s 2ms/step - loss: 0.6072 - accuracy: 0.6813 - val_loss: 0.7501 - val_accuracy: 0.4963
Epoch 

In [0]:
test_data = np.random.randn(5,150)
test_labels = np.random.randint(2, size=(5,1))

In [47]:
model.predict(test_data)

array([[0.50326824],
       [0.30206957],
       [0.21123666],
       [0.8414847 ],
       [0.61358917]], dtype=float32)

In [48]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.50326824],
       [0.30206957],
       [0.21123666],
       [0.8414847 ],
       [0.61358917]], dtype=float32)

In [49]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[1],
       [0],
       [0],
       [1],
       [1]], dtype=int32)

# Example - Multi-class classification

In [0]:
data=np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [56]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [57]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [58]:
labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [59]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3218 - accuracy: 0.0976 - val_loss: 2.3051 - val_accuracy: 0.0980
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3035 - accuracy: 0.1024 - val_loss: 2.3044 - val_accuracy: 0.1080
Epoch 3/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3014 - accuracy: 0.1063 - val_loss: 2.3032 - val_accuracy: 0.1110
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2985 - accuracy: 0.1154 - val_loss: 2.3100 - val_accuracy: 0.0985
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2961 - accuracy: 0.1175 - val_loss: 2.3108 - val_accuracy: 0.0985
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2934 - accuracy: 0.1210 - val_loss: 2.3103 - val_accuracy: 0.0950
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2898 - accuracy: 0.1251 - val_loss: 2.3218 - val_accuracy: 0.0915
Epoch 

In [60]:
test_data = np.random.random((10,150))
model.predict(test_data)

array([[0.10871273, 0.06359933, 0.12670061, 0.16871028, 0.06758382,
        0.07686712, 0.09291117, 0.05456163, 0.17731892, 0.06303446],
       [0.06405486, 0.13134964, 0.12180176, 0.14444488, 0.16261294,
        0.04803033, 0.06078133, 0.09887974, 0.07607341, 0.09197114],
       [0.08788122, 0.14451337, 0.11063496, 0.16370139, 0.09277205,
        0.07360897, 0.07740316, 0.0482108 , 0.10925233, 0.09202179],
       [0.15350333, 0.09396786, 0.10576987, 0.06917609, 0.19370627,
        0.09770711, 0.05900199, 0.10352121, 0.07144238, 0.05220387],
       [0.10617368, 0.13444957, 0.09754603, 0.0623842 , 0.10541813,
        0.09481056, 0.07813738, 0.08399697, 0.11921033, 0.11787309],
       [0.0259263 , 0.0626017 , 0.09702196, 0.10630717, 0.20348245,
        0.03030061, 0.14123674, 0.14080097, 0.09040695, 0.1019151 ],
       [0.09952982, 0.17431924, 0.08297516, 0.05923405, 0.09315633,
        0.11337087, 0.0483271 , 0.17594525, 0.09261782, 0.06052437],
       [0.02438681, 0.07814907, 0.1018226

In [61]:
model.predict_classes(test_data)

array([8, 4, 3, 4, 1, 4, 7, 6, 8, 7])

# Example - Regression

In [0]:
data = np.random.random((10000, 150))
labels = 50* np.random.random(10000)

In [63]:
labels[:10]

array([26.21073021, 39.40128775, 44.78138058, 28.50922211, 31.95954169,
       14.21231112, 27.99304398, 19.9313822 , 39.65961214, 34.17829517])

In [64]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 250.9221 - val_loss: 204.2550
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 211.3017 - val_loss: 204.1487
Epoch 3/30
250/250 [==============================] - 0s 2ms/step - loss: 210.7800 - val_loss: 205.2568
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 210.2064 - val_loss: 204.4431
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 209.9321 - val_loss: 204.7305
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 209.6209 - val_loss: 204.9347
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 209.1161 - val_loss: 205.8216
Epoch 8/30
250/250 [==============================] - 0s 2ms/step - loss: 208.8458 - val_loss: 205.8359
Epoch 9/30
250/250 [==============================] - 0s 2ms/step - loss: 208.5990 - val_loss: 205.7822
Epoch 10/30
250/250 [==============================] - 0s 2ms/st

In [66]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 13.4475 - mse: 254.1118 - val_loss: 12.3007 - val_mse: 206.3385
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 12.5817 - mse: 211.1838 - val_loss: 12.2727 - val_mse: 205.2906
Epoch 3/30
250/250 [==============================] - 0s 2ms/step - loss: 12.5668 - mse: 210.6964 - val_loss: 12.2994 - val_mse: 206.3871
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 12.5373 - mse: 210.4449 - val_loss: 12.3246 - val_mse: 207.4148
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 12.5334 - mse: 210.3590 - val_loss: 12.3299 - val_mse: 207.5506
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 12.5170 - mse: 209.9919 - val_loss: 12.3141 - val_mse: 206.5968
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 12.5001 - mse: 209.4909 - val_loss: 12.3211 - val_mse: 206.8821
Epoch 8/30
250/250 [==============

In [67]:
test_data = np.random.random((10,150))
model.predict(test_data)

array([[25.194326],
       [21.71915 ],
       [17.278536],
       [27.444489],
       [23.748924],
       [29.191406],
       [15.242067],
       [23.020002],
       [28.434217],
       [20.807924]], dtype=float32)